# Generated by Django 4.2.3 on 2023-07-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_certificate_user_alter_certificate_certificate_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='jwt_token_expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=5534981, max_length=7, null=True),
        ),
    ]
