# Generated by Django 4.2.3 on 2023-07-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certificate_jwt_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='jwt_token',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='jwt_token_expires_at',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=1483866, max_length=7, null=True),
        ),
    ]
