# Generated by Django 4.2.3 on 2023-07-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_certificate_jwt_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=8146323, max_length=7, null=True),
        ),
    ]
