# Generated by Django 4.2.3 on 2023-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_certificate_certificate_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='subject',
            new_name='content',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certified_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='header',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=7840123, editable=False, max_length=7, null=True),
        ),
    ]
