# Generated by Django 4.2.3 on 2023-07-26 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_subject_certificate_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=681947, editable=False, max_length=7, null=True),
        ),
    ]
