# Generated by Django 4.2.3 on 2023-07-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_certificate_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=9524755, editable=False, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='content',
            field=models.TextField(blank=True, max_length=450, null=True),
        ),
    ]
