# Generated by Django 4.2.3 on 2023-07-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_certificate_certificate_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_no',
            field=models.CharField(default=4439923, editable=False, max_length=7, null=True),
        ),
    ]
